### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by cwule** [furaga/UnityAvartarRetarget#3]
I like the concept of this asset and bought it on the asset store but without a manual it is really difficult to use. Could you describe how to use it when I want to use my own avatar fbx file?

**Comment by cwule** [comment]
Eg. when I use [this body model](https://free3d.com/3d-model/human-base-riged-85678.html),  attach the unitychanavatar script and replace the joint names 

`var root = gameObject.transform.Find("Character1_Reference").gameObject;
var hips = root.gameObject.transform.Find("Character1_Hips").gameObject;
...`
with 
`var root = gameObject.transform.Find("root").gameObject;
var hips = root.gameObject.transform.Find("pelvis").gameObject;
...`

the results looks like [this](https://imgur.com/a/nuw7LhG):

**Comment by furaga** [comment]
Hi, cwule

Thank you for your purchase and question.

Each avatar script depends on a model structure (bone names, bone hierarchy, their local coordinations, ...)
Your body model might not have the same model structure as unitychan.

The most straightforward solution is to implement a new avatar script for your body model by yourself.

Instead, you might be able to use **AliciaAvatar script**. 
I think Alicia model is VRM format (https://vrm.dev/en/)
Therefore, please try to convert your body model to VRM format with UniVRM (cf. https://vrm.dev/en/univrm/univrm_workflow/)
Then, attach AlicialAvatar to the converted model.

**Comment by cwule** [comment]
Thanks for the info, just using the Alicia script didn't work, I needed to adapt the correctionRightEulers. Right now I was adjusting them manually by trial-and-error until they fit. Is this the right way to go or is there an easier method? Also, there seems to be an issue with the leg though [in all 3 avatars](https://imgur.com/a/SkyN506) right towards the end of the animation.

**Comment by furaga** [comment]
> I needed to adapt the correctionRightEulers. Right now I was adjusting them manually by trial-and-error until they fit. Is this the right way to go or is there an easier method? 

Actually, I also did the try-and-errors for unitychan and alicia.
It might be possible to implement some automatic calibration, but I have not tried.

> Also, there seems to be an issue with the leg though in all 3 avatars right towards the end of the animation.

I think it is a correct behavior, the motion data (CMU Graphics Lab Motion Capture Database ) is originally like so.
You can confirm it if you do 3D-plot of the joint positions of the motion file

**Comment by cwule** [comment]
One more question: If I want to copy the joint positions from another source than the motionplayer, eg. from another avatar, how do I implement that?
Eg. I have a `List<Vector3> poseList` with my own pose positions, which is updated every frame. While it seems simple to replace the if(MotionProvider) input in the LateUpdate with another line that reads the `List<Vector3> poseList`, I am not sure what the syntax should be here?

If I just type 
`pose.Positions = poseList;` 
Unity complains about a null reference even though poseList contains 13 elements.

**Comment by cwule** [comment]
Got it, it's the LSP order as commented in the script http://sam.johnson.io/research/lsp.html
